excluded:
 - Carthage
 - Pods
identifier_name:
  excluded:
    - id
file_length:
  warning: 1000
  error: 1500
line_length: 
  warning: 300 
  error: 350
  ignores_comments: true
  ignores_urls: true
cyclomatic_complexity:
  ignores_case_statements: true
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 10
disabled_rules:
  - nesting
  - todo
  - trailing_whitespace
  - ignores_empty_lines
  - force_unwrapping
  - ignores_comments
